# Generated by Django 2.2.6 on 2019-10-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='school_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='学校名称'),
        ),
    ]
